/**
 * Transform full skills.sh data (16K+ skills) to data.js format
 */
const fs = require('fs');

const INPUT_FILE = '/home/harshith/clawd/skill-directory/data/skills-sh.json';
const OUTPUT_FILE = '/home/harshith/clawd/skill-directory/data.js';

// Category detection from skill name/id
function detectCategory(name, source) {
    const lowerName = name.toLowerCase();
    const lowerSource = (source || '').toLowerCase();
    
    // Frontend
    if (/react|vue|angular|svelte|next|nuxt|frontend|css|tailwind|ui-ux|design|shadcn/.test(lowerName)) {
        return 'Frontend';
    }
    // Backend
    if (/backend|server|api|express|fastapi|django|flask|rails|spring|nest|prisma|postgres|mysql|database|supabase|mongodb/.test(lowerName)) {
        return 'Backend';
    }
    // DevOps
    if (/devops|docker|kubernetes|k8s|terraform|ansible|cicd|deploy|aws|azure|gcp|cloud|infrastructure/.test(lowerName)) {
        return 'DevOps';
    }
    // AI/ML
    if (/ai|ml|llm|gpt|claude|openai|langchain|embedding|vector|transformer|model/.test(lowerName)) {
        return 'AI/ML';
    }
    // Mobile
    if (/mobile|ios|android|swift|kotlin|react-native|expo|flutter/.test(lowerName)) {
        return 'Mobile';
    }
    // Testing
    if (/test|testing|jest|vitest|playwright|cypress|unittest|spec/.test(lowerName)) {
        return 'Testing';
    }
    // Security
    if (/security|auth|oauth|jwt|encryption|vulnerability|audit|secure/.test(lowerName)) {
        return 'Security';
    }
    // Documentation
    if (/doc|readme|writing|content|markdown/.test(lowerName)) {
        return 'Documentation';
    }
    // Marketing
    if (/marketing|seo|ads|social|content|copywriting|email-sequence|analytics/.test(lowerName)) {
        return 'Marketing';
    }
    // Development Tools
    if (/git|debug|lint|format|build|compile|cli|terminal|editor/.test(lowerName)) {
        return 'Development Tools';
    }
    // Clawdbot specific
    if (/clawdbot|clawdhub/.test(lowerSource)) {
        return 'Clawdbot';
    }
    // Agent/Automation
    if (/agent|automat|workflow|task|bot/.test(lowerName)) {
        return 'Agent/Automation';
    }
    
    return 'Other';
}

// Extract tags from skill name
function extractTags(name, source) {
    const tags = [];
    const lowerName = name.toLowerCase();
    
    // Framework/library tags
    const frameworks = ['react', 'vue', 'angular', 'svelte', 'next', 'nuxt', 'expo', 'django', 'flask', 
                        'express', 'fastapi', 'nest', 'spring', 'rails', 'laravel', 'swift', 'kotlin'];
    frameworks.forEach(fw => {
        if (lowerName.includes(fw)) tags.push(fw);
    });
    
    // Technology tags
    const techs = ['typescript', 'javascript', 'python', 'rust', 'go', 'java', 'ruby', 'php', 
                   'docker', 'kubernetes', 'aws', 'azure', 'gcp', 'terraform', 'graphql',
                   'postgres', 'mysql', 'mongodb', 'redis', 'supabase', 'firebase',
                   'tailwind', 'css', 'sass', 'webpack', 'vite', 'esbuild'];
    techs.forEach(tech => {
        if (lowerName.includes(tech)) tags.push(tech);
    });
    
    // Topic tags
    const topics = ['testing', 'security', 'auth', 'api', 'seo', 'marketing', 'devops', 'cicd',
                    'performance', 'accessibility', 'design', 'ui', 'ux', 'mobile', 'web'];
    topics.forEach(topic => {
        if (lowerName.includes(topic)) tags.push(topic);
    });
    
    return [...new Set(tags)].slice(0, 5); // Max 5 unique tags
}

async function main() {
    console.log('Loading skills.sh data...');
    
    const rawData = JSON.parse(fs.readFileSync(INPUT_FILE, 'utf-8'));
    const skills = rawData.skills;
    
    console.log(`Processing ${skills.length} skills...`);
    
    const transformedSkills = skills.map(skill => {
        const source = skill.topSource || '';
        const [author, ...repoParts] = source.split('/');
        const repo = source;
        
        return {
            id: `${source}/${skill.id}`,
            name: skill.name || skill.id,
            author: author || 'unknown',
            repo: repo,
            description: '', // API doesn't provide descriptions
            installs: skill.installs || 0,
            downloads: 0,
            stars: 0,
            category: detectCategory(skill.name || skill.id, source),
            tags: extractTags(skill.name || skill.id, source),
            source: 'skills.sh',
            url: `https://skills.sh/${source}/${skill.id}`,
            installCommand: `npx skills add ${source}/${skill.id}`,
            lastUpdated: new Date().toISOString().split('T')[0]
        };
    });
    
    // Generate the JS file
    const jsContent = `// Auto-generated by transform-full.js
// Last updated: ${new Date().toISOString()}
// Total skills: ${transformedSkills.length}

const skills = ${JSON.stringify(transformedSkills, null, 2)};

// Export for both ES modules and CommonJS
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { skills };
}

// Also export for ES modules
export { skills };
export default skills;
`;

    fs.writeFileSync(OUTPUT_FILE, jsContent);
    
    console.log(`Done! Saved ${transformedSkills.length} skills to ${OUTPUT_FILE}`);
    console.log(`File size: ${(fs.statSync(OUTPUT_FILE).size / 1024 / 1024).toFixed(2)} MB`);
    
    // Category distribution
    const categories = {};
    transformedSkills.forEach(s => {
        categories[s.category] = (categories[s.category] || 0) + 1;
    });
    console.log('\nCategory distribution:');
    Object.entries(categories)
        .sort((a, b) => b[1] - a[1])
        .forEach(([cat, count]) => console.log(`  ${cat}: ${count}`));
}

main();
